### ISSUE TITLE
Memory bank features normalization 

### ISSUE THREAD

**Issue by sirkosophia** [vpariza/open-hummingbird-eval#5]
In the create_memory features of the memory bank seem to be normalized along the spatial dimension. I believe this is a bug, maybe the dimension should be specified as "-1" instead of dim=1, although there is another normalization done further in the code.

**Comment by vpariza** [comment]
Hello @sirkosophia,

Thank you very much for pointing this out. You are absolutely correct.
There is this small issue in the uploaded source code.

Unfortunately, we had fixed this in our local hummingbird evaluation for our publication but did not push it yet here.
We also finished the evaluation on ADE20k. I will try to push all the changes tomorrow.

Thanks again for pointing it out though.

**Comment by vpariza** [comment]
Hello @sirkosophia again,

We investigated the effect of this small change in the code and it consistently and minimally affects better the performance of all the algorithms we tried.

You can see below the results of different algorithms on the Pascal VOC (Augmented) with 512 image size.

<table>
  <tr>
    <th> Model </th>
    <th> Type </th>
    <th>mIoU With Mistake </th>
    <th>mIoU Without Mistake </th>
  </tr>
    <td>ViT-S/16</td>
    <td>DINO</td>
    <td>47.9</td>
    <td>48.7</td>
  </tr>
  </tr>
    <td>ViT-S/16</td>
    <td>SelfPatch</td>
    <td>50.1</td>
    <td>50.8</td>
  </tr>
  </tr>
    <td>ViT-S/16</td>
    <td>CrOC</td>
    <td>59.5</td>
    <td>60.5</td>
  </tr>
  </tr>
    <td>ViT-S/16</td>
    <td>TimeT</td>
    <td>61.3</td>
    <td>62.3</td>
  </tr>
  </tr>
    <td>ViT-S/16</td>
    <td>Leopart</td>
    <td>63.4</td>
    <td>64.5</td>
  </tr>
  </tr>
    <td>ViT-S/16</td>
    <td>CrIBo</td>
    <td>71.2</td>
    <td>72.4</td>
  </tr>
  </tr>
    <td>ViT-S/14</td>
    <td>DINOv2R</td>
    <td>73.8</td>
    <td>75.0</td>
  </tr>
  </tr>
    <td>ViT-S/14</td>
    <td>NeCo</td>
    <td>78.9</td>
    <td>80.2</td>
  </tr>
  </tr>
    <td>ViT-Β/16</td>
    <td>MAE</td>
    <td>6.9</td>
    <td>7.0</td>
  </tr>
  </tr>
    <td>ViT-Β/16</td>
    <td>DINO</td>
    <td>56.5</td>
    <td>57.3</td>
  </tr>
  </tr>
    <td>ViT-Β/16</td>
    <td>Leopart</td>
    <td>68.2</td>
    <td>69.5</td>
  </tr>
  </tr>
    <td>ViT-Β/16</td>
    <td>CrIBo</td>
    <td>73.1</td>
    <td>74.2</td>
  </tr>
  </tr>
    <td>ViT-Β/14</td>
    <td>DINOv2R</td>
    <td>76.2</td>
    <td>77.3</td>
  </tr>
  </tr>
    <td>ViT-Β/14</td>
    <td>NeCo</td>
    <td>82.2</td>
    <td>83.5</td>
  </tr>
</table>

I am closing the issue as it seems closed. Please reopen It if you have further questions.
