### ISSUE TITLE
Reproducibility of the code 

### ISSUE THREAD

**Issue by rm-wu** [vpariza/open-hummingbird-eval#7]
Hi! Thanks a lot for your work, I think it's a very useful reimplementation of the evaluation setup from Hummingbird's paper that could benefit a lot of researcher. 
However, I found some problems when trying to use the repo. First, a proper `environment.yml` file is missing and that could lead to some potential issues, with multiple people using the code. Could you please provide a way to reproduce your environment? 
Second, I tried to download the of the VOC dataset is not working
```bash
!wget -O voc_data.zip "https://cpf5rw.am.files.1drv.com/y4mxW5pUDPP2WOVWXZYdhd5PK82qXcqQURFvVTXGSfEk8igihjx8oyA_iSmeuMnwLSyNwN601Jq9Ec9PyN3olpCCCoNtrgYg7DkvrXUXyI-mymjQiSR0kgRZDvRRUw4SD9i4QFTa-q5W_A7WahXU5v1XroWUU8bKDgUbY0xbBuX67xZr4HGDQiT5b0cr4iPQbt6NJlKkAyWdXUkIL37xpL3JQ"
```
That's the error I get (I also tried on Colab and I get the same result)
```bash
--2024-11-12 15:00:52--  https://cpf5rw.am.files.1drv.com/y4mxW5pUDPP2WOVWXZYdhd5PK82qXcqQURFvVTXGSfEk8igihjx8oyA_iSmeuMnwLSyNwN601Jq9Ec9PyN3olpCCCoNtrgYg7DkvrXUXyI-mymjQiSR0kgRZDvRRUw4SD9i4QFTa-q5W_A7WahXU5v1XroWUU8bKDgUbY0xbBuX67xZr4HGDQiT5b0cr4iPQbt6NJlKkAyWdXUkIL37xpL3JQ
Resolving cpf5rw.am.files.1drv.com (cpf5rw.am.files.1drv.com)... 13.107.42.12
Connecting to cpf5rw.am.files.1drv.com (cpf5rw.am.files.1drv.com)|13.107.42.12|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-12 15:00:53 ERROR 404: Not Found.
```

**Comment by rm-wu** [comment]
This could be an `environment.yml` file based on your `README.md` file:
```yaml
name: hummingbird-eval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip
  - numpy=1.26.4
  - joblib=1.4.2
  - pip:
    - torchmetrics=1.5.2
    - scann=1.3.4
    - pillow
    - tqdm
    - matplotlib
    - pandas
```

**Comment by vpariza** [comment]
Hi @rm-wu,

Many thanks to the issue you opened regarding the two issues.

1) I will provide a working environment.yml soon in the repo.

2) I updated the links in the notebook (https://github.com/vpariza/open-hummingbird-eval/blob/main/examples/hbird_eval_example.ipynb).

**Comment by vpariza** [comment]
@rm-wu 

I have added an environment file and remove the wget links to the dataset sine they do not work as is with one drive object shareable links.

Thank you again for your help.

I am closing the issue now.
